### ISSUE TITLE
fatal: repository 'https://bitbucket.org/s_l_teichmann/simplexnoise/' not found

### ISSUE THREAD

**Issue by viplifes** [peterhellberg/karta#2]
Thanks for this wonderful project. I get an error. Could you help solve the problem?

go install github.com/peterhellberg/karta/cmd/karta@latest

go: finding module for package github.com/pzsz/voronoi
go: finding module for package bitbucket.org/s_l_teichmann/simplexnoise
go: finding module for package github.com/pzsz/voronoi/utils
go: finding module for package github.com/llgcode/draw2d/draw2dimg
go: found github.com/llgcode/draw2d/draw2dimg in github.com/llgcode/draw2d v0.0.0-20210904075650-80aa0a2a901d
go: found github.com/pzsz/voronoi in github.com/pzsz/voronoi v0.0.0-20130609164533-4314be88c79f
go: found github.com/pzsz/voronoi/utils in github.com/pzsz/voronoi v0.0.0-20130609164533-4314be88c79f
go: finding module for package bitbucket.org/s_l_teichmann/simplexnoise
../../go/pkg/mod/github.com/peterhellberg/karta@v0.0.0-20210816102308-fc99260efb50/noise/noise.go:3:8: cannot find module providing package bitbucket.org/s_l_teichmann/simplexnoise: module bitbucket.org/s_l_teichmann/simplexnoise: git ls-remote -q origin in /Users/dimir/go/pkg/mod/cache/vcs/2b6156a231bb81581fe42a1b84979a1c525744be6d29826c2b9adf2fabd377d8: exit status 128:
	remote: You may not have access to this repository or it no longer exists in this workspace. If you think this repository exists and you have access, make sure you are authenticated.
	fatal: repository 'https://bitbucket.org/s_l_teichmann/simplexnoise/' not found

**Comment by peterhellberg** [comment]
@viplifes I've now replaced the library used for simplex noise generation.

I have also created a module and updated the [Installation](https://github.com/peterhellberg/karta#installation) instructions. I hope this solves the issue 😃

**Comment by viplifes** [comment]
Perfect! Thank you very much!
